config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :tasks, only: [:new, :create, :destroy] do
    member do
      post "completed" => "task_completions#create"
    end
  end

  constraints Monban::Constraints::SignedIn.new do
    root "tasks#index"
  end

  constraints Monban::Constraints::SignedOut.new do
    root "homes#show", as: :home
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  validates :content, presence: true

  def complete!
    update(completed: true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_many :names
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Monban::ControllerHelpers
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    @task = Task.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/task_completions_controller.rb
class TaskCompletionsController < ApplicationController
  def create
    task = Task.find(params[:id])
    task.completed = true
    task.save

    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save

      render @task
    else
      render partial: "application/form_errors", status: 422, locals: {object: @task}
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy

    head 200
  end

  private

  def task_params
    params.require(:task).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_form_errors.html.erb
<% if object.errors.any? %>
  <p>We can not save your object.</p>
   <li>
    <% object.errors.full_messages.each do |error_message| %>
       <%= error_message %>
    <% end %>
   </li>
<% end %> 

app/views/homes/show.html.erb
<h1>Hi <%= current_user.name %>, welcome to tasker</h1>
<h2>Here are your tasks</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
  <%= link_to "Sign out", session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_session_path %>
  <%= link_to "Sign up", new_user_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/tasks/_task.html.erb
<li class="<%= "completed" if task.completed? %>">
  <%= task.content %>
  <%= button_to "Completed", completed_task_path(task), form_class:"completed-task" %>
  <%= button_to "Delete", task_path(task), form_class:"delete-task", method: :delete %>
</li>

app/views/tasks/index.html.erb
<h1><%= current_user.name %>'s tasks</h1>

<div id="errors"></div>

<ul id="task-list">
  <%= render current_user.tasks.order(created_at: :desc) %>
</ul>

<h3>new task for <%= current_user.name %></h3>

<%= form_for @task do |form| %>
  <%= form.label :content %>
  <%= form.text_field :content %>
  <%= form.submit %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>